// urlConstants
export const BASE_URL = import.meta.env.VITE_REACT_APP_BACKEND_URL;
//export const BASE_URL = 'http://13.202.10.183:8000'; // Your base URL
// export const BASE_URL = 'https://mzfndqs3-8000.use.devtunnels.ms'
export const URLS = {
  LOGIN: `${BASE_URL}/auth/login/`,
  REGISTER_INDIVIDUAL: `${BASE_URL}/auth/signup/`,
  REGISTER_INDIVIDUAL_VERIFY: `${BASE_URL}/auth/signup-verify/`,
  REGISTER_ORGANISATION: `${BASE_URL}/org/signup/`,
  LOGOUT: `${BASE_URL}/auth/logout/`,
  USER_PROFILE: `${BASE_URL}/user/profile`,
  FORGOT_PASSWORD_OTP: `${BASE_URL}/auth/forgot-password/send-otp/`,
  FORGOT_PASSWORD_OTP_VERIFY: `${BASE_URL}/auth/forgot-password/verify/`,
  FORGOT_PASSWORD_CHANGE: `${BASE_URL}/auth/change-password/`,
  FORGOT_PASSWORD_RESET: `${BASE_URL}/auth/forgot-password/reset/`,
  GOOGLE_LOGIN: `${BASE_URL}/auth/google-login/`,
  APPLE_LOGIN: `${BASE_URL}/auth/web-apple-login/`,
  PASSWORD_CHANGE: `${BASE_URL}/auth/change-password/`,
  FETCH_USER: `${BASE_URL}/auth/user/`,
  IMAGE_UPLOAD: `${BASE_URL}/auth/user/`,
  // Add more URLs as needed
  SAVE_ACCOUNT_DETAILS: `${BASE_URL}/auth/user/`,
  DELETE_USER: `${BASE_URL}/auth/delete-user/`,
  NOTIFICATIONS: `${BASE_URL}/notifications/`,
  PROJECTS: `${BASE_URL}/proj/models/`,
  DELETE_MODELS: `${BASE_URL}/proj/delete-model/`,
  CART: `${BASE_URL}/cart/`,
  USER_ADDRESS: `${BASE_URL}/auth/address/`,
  ORDER_ID: `${BASE_URL}/payments/razorpay/buy-views/`,
  PRICE_DETAILS: `${BASE_URL}/payments/price-details`,
  GLD_UPLOAD: `${BASE_URL}/proj/model-upload/`,
  FILE_UPLOAD: `${BASE_URL}/proj/file-upload/`,
  GET_INVOICES: `${BASE_URL}/payments/get-invoices/`,
  DOWNLOAD_INVOICES: `${BASE_URL}/payments/download-invoice/`,
  RETRIEVE_MODEL: `${BASE_URL}/proj/retrieve-model/`,
  GENERATE_MODEL: `${BASE_URL}/proj/generate-model/`,
  RESEND_OTP: `${BASE_URL}/auth/resend-otp/`,
  BATCH_UPLOAD: `${BASE_URL}/proj/models/`,
  GET_IMAGES: `${BASE_URL}/proj/get-files`,
  DELETE_IMAGES: `${BASE_URL}/proj/delete-images/`,
  USER_PREFERENCES: `${BASE_URL}/auth/user-preferences/`,
  CONVERT_MODEL: `${BASE_URL}/proj/convert-usdz-to-glb/`,
  SUPPORT_TICKET: `${BASE_URL}/support/ticket/`,
  TICKET_CATEGORIES: `${BASE_URL}/support/ticket-categories/`,
  MODEL_SHARE: `${BASE_URL}/proj/share/`,
};
